### ISSUE TITLE
Request to Maintain Repo

### ISSUE THREAD

**Issue by NikDevx** [homebridge/unmaintained-plugins#17]
* **Plugin Name:**
[homebridge-philips-air](https://github.com/homebridge-plugins/homebridge-philips-air)

* **References:**
[homebridge-temperature-humidity-sensor-file](https://github.com/NikDevx/homebridge-temperature-humidity-sensor-file) - my project
[ps5-wake](https://github.com/iharosi/ps5-wake) - helped

**Comment by Sunoo** [comment]
As the former maintainer of this plugin, I support transitioning this to @NikDevx. They've already started making some updates to the plugin, and have experience with other Homebridge plugins.

**Comment by donavanbecker** [comment]
@NikDevx you will have to delete your fork of homebridge-philips-air before I can transfer this over to you.

**Comment by donavanbecker** [comment]
[philips-air](https://github.com/homebridge-plugins/philips-air) repo has been transfered. So just need to finish this one.

**Comment by NikDevx** [comment]
> @NikDevx you will have to delete your fork of homebridge-philips-air before I can transfer this over to you.

Hello @donavanbecker 
I never do this thing before.
Can you help me please?

**Comment by donavanbecker** [comment]
Click here https://github.com/NikDevx/homebridge-philips-air.
Then click Settings
Scroll to the bottom and click Delete this repository

**Comment by NikDevx** [comment]
@donavanbecker Thanks a lot! Done!

**Comment by donavanbecker** [comment]
@NikDevx okay Github should be done. Did you get the npm request?

**Comment by NikDevx** [comment]
@donavanbecker Yes. I got it in npm

**Comment by donavanbecker** [comment]
@NikDevx Should be good to go then?

**Comment by NikDevx** [comment]
> @NikDevx Should be good to go then?

@donavanbecker Yes. Thank you.

**Comment by donavanbecker** [comment]
@NikDevx I don't think you have accepted the GitHub repo yet.

**Comment by NikDevx** [comment]
> @NikDevx I don't think you have accepted the GitHub repo yet.

@donavanbecker  Where I can check it? :)

**Comment by donavanbecker** [comment]
@NikDevx Make sure you don't have a forked repo. Then check your email to accept the transfer

**Comment by NikDevx** [comment]
@donavanbecker Done. Thanks!

**Comment by donavanbecker** [comment]
You should also have one for Philip-airs repo

**Comment by NikDevx** [comment]
@donavanbecker I added 2 repo
