### ISSUE TITLE
Request to Abondon Plugin

### ISSUE THREAD

**Issue by SmolSoftBoi** [homebridge/unmaintained-plugins#21]
* **Plugin Name:** Homebridge TP-Link Powerline Platform Plugin

* **NPM Ownership Change Completed:**  NO 

* **GitHub Ownership Change Completed:**  NO

**Comment by donavanbecker** [comment]
@SmolSoftBoi Can you transfer them to me? Once you transfer them to me then I can transfer them to the organization.

**Comment by SmolSoftBoi** [comment]
> @SmolSoftBoi Can you transfer them to me? Once you transfer them to me then I can transfer them to the organization.

Transferred.

**Comment by donavanbecker** [comment]
Plug-in has been transferred to Homebridge-plugin repo.

**Comment by SmolSoftBoi** [comment]
> Have you transferred on npm?

I've added you on npm, but I am unsure how to transfer.

**Comment by donavanbecker** [comment]
@SmolSoftBoi Okay all should be good. Thanks!

If verified, I will remove and then close this issue.
