### ISSUE TITLE
Request to Abondon Plugin

### ISSUE THREAD

**Issue by poblouin** [homebridge/unmaintained-plugins#27]
* **Plugin Name:**
[homebridge-spotify-speaker
](https://github.com/poblouin/homebridge-spotify-speaker)

* **NPM Ownership Change Completed:** YES - completed

* **GitHub Ownership Change Completed:** YES - currently with bwp91 waiting to transfer to homebridge

**Comment by bwp91** [comment]
Hi @poblouin 

If you are happy to continue, please can you transfer the repo to myself (both on GitHub and NPM, my username is `bwp91` in both places.

Then I can transfer them to this unmaintained-plugins repo until a new owner is found.

Thanks!
