### ISSUE TITLE
Request to Maintain Repo

### ISSUE THREAD

**Issue by joeyhage** [homebridge/unmaintained-plugins#28]
* **Plugin Name:**
[homebridge-spotify-speaker](https://github.com/poblouin/homebridge-spotify-speaker)

* **References:**
I have made a contribution to [homebridge-spotify-speaker](https://github.com/poblouin/homebridge-spotify-speaker) in the past.

**Comment by bwp91** [comment]
Here comes the technicalities 🤨

I don't think it will allow me to transfer a repo to your github account if you already have one with the same name.

any way you could get around this? if you wanted to continue on the original `homebridge-spotify-speaker` repo?

**Comment by joeyhage** [comment]
Yeah, that shouldn't be a problem. I created a patch of the changes I made and deleted the repo. I also have a copy locally. Should be good to go!

**Comment by joeyhage** [comment]
@bwp91 let me know if you need anything else from me. There’s a bug in the plugin I’d like to get out because it’s causing accessories to persist even after being removed from the plugin config. Thanks!

**Comment by bwp91** [comment]
Hi @joeyhage sorry for the delay on this i ironically lost permissions to transfer a github repo when i transferred to the homebridge group.

Working on this!

With regards to the npm package, i won’t be able to transfer to you since it was scoped to the other user ie the plugin was `@user/homebridge-*`.

However we can deprecate this on npm and put a message to use your npm published plugin

**Comment by joeyhage** [comment]
@bwp91 no worries! Thanks! Before we publish a deprecation notice, I think I will change my npm plugin name and remove @joeyhage so it can be transferred more easily down the line if I am unable to maintain

**Comment by joeyhage** [comment]
^ I don’t foresee being unable to maintain but I want to avoid any future NPM deprecations.

**Comment by bwp91** [comment]
is the npm package `homebridge-spotify-speaker` available? if so i’d recommend publishing and grabbing this asap

**Comment by joeyhage** [comment]
snagged it
