### ISSUE TITLE
Request to Maintain Repo

### ISSUE THREAD

**Issue by tillkruss** [homebridge/unmaintained-plugins#30]
* **Plugin Name:**
homebridge-purpleair

* **References:**
https://github.com/tillkruss/homebridge-purpleair

**Comment by bwp91** [comment]
Are you on the Homebridge discord channel?

**Comment by tillkruss** [comment]
Yep, let me ping you.

**Comment by tillkruss** [comment]
- Deprecated https://www.npmjs.com/package/@tillkruss/homebridge-purpleair
- Published to https://www.npmjs.com/package/homebridge-purpleair
- Archived https://github.com/tillkruss/homebridge-purpleair-old
