### ISSUE TITLE
Request to Abandon Plugin

### ISSUE THREAD

**Issue by duculete** [homebridge/unmaintained-plugins#31]
* **Plugin Name:**
homebridge-gree-ac

* **NPM Ownership Change Completed:** 
YES

* **GitHub Ownership Change Completed:** 
YEA

**Comment by donavanbecker** [comment]
@duculete please give username `donavanbecker` access to nom package and transfer to that username on GitHub.  From there I will move it to the Homebridge-Plugin Orgnization.

**Comment by bwp91** [comment]
@donavanbecker 

was planning this repo for this plugin requesting verification:

https://github.com/homebridge/verified/issues/575

**Comment by bwp91** [comment]
Any updates here?

**Comment by donavanbecker** [comment]
I haven't received the repos yet on GitHub or npm

**Comment by bwp91** [comment]
Thank you @duculete
