### ISSUE TITLE
Request to Maintain Repo

### ISSUE THREAD

**Issue by eibenp** [homebridge/unmaintained-plugins#32]
* **Plugin Name:**
homebridge-gree-ac

* **References:**
[homebridge-gree-airconditioner](https://github.com/eibenp/homebridge-gree-airconditioner)

**Comment by eibenp** [comment]
Hi @bwp91 

yes, my npm package username is `eibenp`.

No, I don't need 2 repos for the same purpose. I don't need the original one.

**Comment by bwp91** [comment]
Hi @eibenp 

Request to become a maintainer of npm package `homebridge-gree-ac` has been sent

**Comment by eibenp** [comment]
Hi @bwp91 

I have accepted the request. Now I am the maintainer of `homebridge-gree-ac` npm package.

**Comment by bwp91** [comment]
Nice, feel free to remove me as a maintainer.

Will close the issue here and reply properly back in the "verification" issue
