### ISSUE TITLE
Request to Maintain Repo

### ISSUE THREAD

**Issue by justjam2013** [homebridge/unmaintained-plugins#34]
* **Plugin Name:**
Homebridge Virtual Device - homebridge-virtual-device

* **References:**
None.
I have opened issues with other plugins, but many appear to either abandoned, or the response time is non-existent. To this end, I have made a post to reddit about creating a plugin repository: [Bring plugins into Homebridge project?](https://www.reddit.com/r/homebridge/comments/1fwryg6/bring_plugins_into_homebridge_project/).
I figured that I should put my money where my mouth is and this plugin look like a great successor to Nick Farina's ["Dummy Switches" Plugin](https://www.npmjs.com/package/homebridge-dummy). I have also noticed that this plugin is not available through NPM, which means that it's not available to install on Homebridge via the UI and therefore will not be found by many users of Homebridge.
I am a software engineer.
Lanuages: primarily Java, Scala, Python; some Visual C#, Visual Basic, C; limited C++, Fortran, Cobol, Forth.
Platforms: AWS, Spring, Servlets, JavaBeans, ...
I am confident that I can pick up Typescript and Homebridge API.
This plugin is currently unmaintained and languishing, so what's the worst that can happen?

**Comment by donavanbecker** [comment]
Approved, Transferring repo.

**Comment by justjam2013** [comment]
Accepted transfer.
