### ISSUE TITLE
Request to Maintain Repo

### ISSUE THREAD

**Issue by bwp91** [homebridge/unmaintained-plugins#9]
* **Plugin Name:**

homebridge-platform-wemo 

* **References:**

[homebridge-ewelink](https://github.com/bwp91/homebridge-ewelink)
[homebridge-govee](https://github.com/bwp91/homebridge-govee)

**Comment by oznu** [comment]
As long as you don't break my wall light switch I'm ok with this 😄 

Tagging @donavanbecker for confirmation.

**Comment by bwp91** [comment]
> As long as you don't break my wall light switch I'm ok with this 😄

At least I'll have the perfect person to turn to if I do 🤣

**Comment by donavanbecker** [comment]
@bwp91 I will do the transfer. We would appreciate it if you would decided to not maintain it anymore to transfer it back to the homebridge-plugin organization so that we can keep it till the next user wants to maintain it, if it ever comes to that :).

**Comment by donavanbecker** [comment]
@bwp91 I have sent the request to transfer homebridge-platform-wemo to you. would you like me to transfer the plugin on npm also?

if so, what is your username?

**Comment by bwp91** [comment]
Yes please. My username on there is bwp91

**Comment by donavanbecker** [comment]
> Yes please. My username on there is bwp91

okay everything should be transferred. Once verified can you close this issue?

**Comment by bwp91** [comment]
Hi @donavanbecker and @oznu 
All seems good re the transfers.
Thanks for putting your trust in me :)
